### ISSUE TITLE
JSON Parser issue

### ISSUE THREAD

**Issue by callefoss** [hbldh/flask-pybankid#1]
Parsing the collect call fails with error: 

raise TypeError(repr(o) + " is not JSON serializable")

**Comment by hbldh** [comment]
Handled in hbldh/pybankid#8.

**Comment by hbldh** [comment]
Updated requirements to PyBankID 0.4.0 in 30a690f707f0d23325678bb46b05ab12c5322804. Rleased in version 0.2.0 of this library and now available on PyPI.
